### ISSUE TITLE
How use TextureNoTile in visual shader?

### ISSUE THREAD

**Issue by LandstalkerZero** [SIsilicon/Tile-Breaker-Plugin#4]
I cant find how use this node, whatewer i plase it (before or after texture) after i connect it to albedo shader give error "No matching function found for 'textureNoTile'" "vec4 ntile_19742 = textureNoTile(n_in2p3, UV.xy, n_in2p1, n_in2p2, n_in2p3);"

**Comment by SIsilicon** [comment]
Fixed as of commit https://github.com/SIsilicon/Tile-Breaker-Plugin/commit/cf42fd80ff866bf86e979c7e11f2e56099e75e68. Thank you for reporting the bug. :)
