### ISSUE TITLE
Visual shader script error<null>

### ISSUE THREAD

**Issue by LandstalkerZero** [SIsilicon/Tile-Breaker-Plugin#5]
Well after fixing one problem another come.
"Visual shader script error<null>: Expected expression, found: COLON'"
"vec4 ntile_24131 = textureNoTile(, n_out11p0.xy, n_in20p1, n_in20p2, n_in20p3);"
Maybe i do somthing wrong and its not shader error.
Godot version 3.2 and 3.2.3
![vsh_1](https://user-images.githubusercontent.com/63158061/99349940-3e535000-28ae-11eb-901c-2df1256f3c54.png)
![vsh_2](https://user-images.githubusercontent.com/63158061/99349955-457a5e00-28ae-11eb-87c2-78727e265e57.png)
![vsh_3](https://user-images.githubusercontent.com/63158061/99349959-47dcb800-28ae-11eb-9670-9ae5454263e6.png)

**Comment by SIsilicon** [comment]
You didn't seem to connect any texture to the TextureNoTile node.

**Comment by LandstalkerZero** [comment]
What exacly texture i need use or node for texture, i dont undestand.
![vsh4](https://user-images.githubusercontent.com/63158061/99402192-230e3200-28fa-11eb-87d1-db448eb0b6db.png)

**Comment by SIsilicon** [comment]
You need to add a texture uniform node and connect its `sampler2D` output to the `sampler2D` input of TextureNoTile. Setup the texture uniform with the texture of your choice.
Let me explain the TextureNoTile's inputs.
- UV is the uv coordinates of where the texture gets sampled at.
- rotation is how randomly the texture gets rotated to help break tiling.
- blending is how much the seams from breaking tiling get smoothed away.
- sampler2D is the texture itself.

What you're doing right now is sampling a texture with a regular texture node, and them using its colour as UV coordinates.

**Comment by LandstalkerZero** [comment]
Thank you, now it work. I forget about inspector parametr so it take time.
